### ISSUE TITLE
Offline player does not start on ChromeOS if disconnected form internet

### ISSUE THREAD

**Issue by mfisher11** [Rise-Vision/offline-player#40]
Steps to reproduce:
* Starting with a player correctly configured for kiosk mode and the player set to start automatically:
1. Disconnect ethernet cable (or remove wireless network configuration). 
2. Reboot Chromebox (or power it on, if it was in an off state).

Result:
Device will boot up, then show the application starting screen for a second or two, then exit to a login prompt.  A dialog bubble will then appear near the bottom left (briefly, perhaps) saying "Darn, the kiosk application could not be launched"

How it should work:
The presentation should start.

Link to Presentation:
This URL has been scheduled to the offline player throughout testing:
http://rise-vision.github.io/content-demo-navigation/index.html

OS:
ChromeOS

Chrome Ver:
43.0.2357.130

**Comment by mfisher11** [comment]
This has been resolved.  Closing.

**Comment by richardszalay** [comment]
Out of interest, what was the cause of the error? We're seeing the same problem on a different project.

**Comment by tejohnso** [comment]
@richardszalay see https://developer.chrome.com/apps/manifest/offline_enabled

**Comment by richardszalay** [comment]
Thanks, it was actually the lack of "kiosk_enabled" that was causing us problems. Definitely an RTFM solution.
