### ISSUE TITLE
In rva-test (may be the same code/version as rva) operating system and player version are incorrect

### ISSUE THREAD

**Issue by mfisher11** [Rise-Vision/offline-player#47]
Steps to reproduce:
1. Sign into RVA (the offline players are in rva-test/kc_uptime, but I think it's the same version)
2. View the display properties for an offline player

Result:
"Player Version" incorrectly shows OfflinePlayer 0.0.1
On ChromeOS (only) Player version shows "undefined undefined" and  OS shows "undefined"

How it should work:
Player version should correctly reflect installed version
On ChromeOS, it should reflect the correct OS

Link to Presentation:
N/A

OS:
Xubuntu 15.04

Chrome Ver:
43.0.2357.134

**Comment by tejohnso** [comment]
I made some corrections to the player and updated **Offline Player - Ubuntu**.  The version info looks okay now.
![offline player - ubuntu](https://cloud.githubusercontent.com/assets/1511535/8760183/9685850a-2cdc-11e5-8950-133ec2cfc049.png)

**Comment by mfisher11** [comment]
@tejohnso Looks good on Linux, sir!  There are still a couple of problems on other platforms, though.

Player version for Mac still shows OfflinePlayer 0.0.1  (OS says MacIntel, so that's fine).
Player version for ChromeOS shows "undefined undefined" and OS says "undefined"
Player version for windows OfflinePlayer 0.0.1 (OS says Win32, so that's fine).

Thanks!

**Comment by tejohnso** [comment]
Can you tell me which machines are being used?  I'd like to check them out with screenconnect.

**Comment by mfisher11** [comment]
@tejohnso The screenconnect company is *KC_Uptime_OfflinePlayer.  ChromeOS is omitted, of course, but the other 3 platforms are in there.  If the mac is offline or in a weird state it's because Mat has it with him and may still be (occasionally) pulling his data off of it.   I'll be doing a bit more testing on Windows and Linux (so they may be up and down).

**Comment by tejohnso** [comment]
@mfisher11 These details are set when the display is registered.  I went into the windows machine and re-registered the displayId and now the version info shows correctly.

**Comment by mfisher11** [comment]
@tejohnso I see.  Thanks.  I'll do the same on the other boxes and if all it well, I'll close this out.

**Comment by mfisher11** [comment]
@tejohnso Re-registering the players took care of it.  OS and Player versions are showing up in all platforms.  ChromeOS is showing Linuxx86_64, and while technically that is correct--do we want that to be the way chrome os is identified?  BTW, the linux nucs are listed as Linuxi686, for comparison.

**Comment by tejohnso** [comment]
@mfisher11 I've improved the platform os information as of version 0.2.2260 of the Offline Player.  Confirmed on the windows offline player uptime box.  I don't see a chrome os machine in the KC Offline Player uptime group so I didn't test that.

**Comment by mfisher11** [comment]
@tejohnso Confirmed on chromeOS, linux and osx.  Closing issue.  BTW, chromeos isn't in SC because it isn't compatible.  Thanks!
