### ISSUE TITLE
When player starts without network connection with previous rise storage content you see "the file or directory could not be found"

### ISSUE THREAD

**Issue by mfisher11** [Rise-Vision/offline-player#49]
Steps to reproduce:
1. Assign rise storage hosted URL to player: https://storage.googleapis.com/risemedialibrary-b428b4e8-c8b9-41d5-8a10-b4193c789443/content-restaurant-promotion/index.html
2. Launch player with network connected  (content will show)
3. Exit player, disconnect from network, reboot/restart player

Result:
Once "splash" screen disappears, you will be left with a white screen that says:
"the file or directory could not be found"

How it should work:
The presentation should be displayed from the local storage

Additional Information:
I'm attaching two screenshots of the debug console.  It looks like there is an access/permissions problem when trying to read the stored content.

Link to Presentation:
N/A

OS:
Windows, Linux, probably ChromeOS

Chrome Ver:
42.0.2311.152 (linux version for stability reasons)
43.0.2357.134 (windows version)

![linux](https://cloud.githubusercontent.com/assets/10407181/8755748/d9bc16b2-2c92-11e5-8df8-511a5dc05f8b.png)
![windows](https://cloud.githubusercontent.com/assets/10407181/8755747/d9a5dff0-2c92-11e5-8a81-8577011d0db4.png)

**Comment by tejohnso** [comment]
I've made some changes that should improve things.  However while looking at the **Offline Player - Ubuntu** instance I noticed an Insufficient Disk Space error was coming up in the console at startup while online.  The local caching won't be in effect there because we need at least 500MB available.

**Comment by mfisher11** [comment]
@tejohnso I'm still seeing the exact same thing as the previous screenshots.  I'll double check Linux again (after de/re-registering the player) but since you just did that on windows and I'm not seeing anything different on that one either, I doubt that will fix it.  Also, there's 1.3G free on the linux player so that shouldn't be a problem.

**Comment by tejohnso** [comment]
It looks like the file space reporting api isn't working on windows.  It's always showing used space = granted space and so no space is remaining.  This is happening on CAP as well.  I'm investigating further to see if cap caching is working.

**Comment by mfisher11** [comment]
@tejohnso Saved content appeared on all of the displays even when internet access was disabled.  I'll close this ticket out now, but to recap what we talked about earlier (so a note can be made or whatever):

The only thing that had changed between when it wasn't working and now, was that I had freed up additional storage.  You coded in a hard limit of 500 megs required to be free.  On all of these devices there was over 1 gig free.  I cleared up some additional space (making over 2 gigs free), and now it works.

It's possible that that is a coincidence.  But *a* theory is that chrome places additional constraints beyond what the apps do.  Perhaps if there is less than 2G (or so) available, the browser will not allow anything to be saved.  Some additional testing may be required for that to be conclusive.

**Comment by ByronDarlison** [comment]
@tejohnso any idea about the space difference @mfisher11 noted above? Thanks

**Comment by tejohnso** [comment]
I'm still not sure why I was seeing 0 bytes available.  I went back in the console command history and ran the same commands with a different result.  They're always returning some  non-zero amount available now.  

But Chrome is definitely adding its own space restrictions.  If I set the file space available to 1GB and ask for space I'll get some fraction of 1GB allocated.  Then we do our own 500MB reduction on top of that so we may end up with "no space" even though the drive has more than 500MB available.

**Comment by ByronDarlison** [comment]
@tejohnso given this how much space should we be telling users we recommend that they have on their devices in order for caching to work at a minimum? What is the baseline that needs to be free and they need to add to that for the amount of content that they want to store?

Thanks

@btfrise @alanclayton

**Comment by tejohnso** [comment]
If we say at least **2GB** free we should be okay.  If they want to cache hundreds of megs of data they'll run into the limit pretty quickly.  But it'll be functional at **2GB**.

**Comment by tejohnso** [comment]
It's questionable whether we should be putting our own 500MB buffer on top of the buffer that chrome is already including when allocating space.

**Comment by ByronDarlison** [comment]
@tejohnso should we lower the 500mb? And to confirm, what I am trying to figure out is what we say they need to have at a minimum of free space to use Player, without cache, and then they should plan on adding free space on top of that to the level that they need for the content that they feel they want to keep locally. Follow me? Thanks

**Comment by tejohnso** [comment]
Oh.  To use player without cache they just need Chrome.  So we can repeat whatever Chrome's minimums are.  For caching, they should have at least a gig free on top of the base chrome install.  And then whatever additional space they need on top of that depending on their expected files.  So if they're caching a 500MB movie, then they should have 1.5 gigs free when they start chrome.

I don't think we should bother with our own 500MB buffer.  Chrome isn't going to let us overrun the disk.

**Comment by ByronDarlison** [comment]
@tejohnso perfect. @alanclayton @btfrise should we note the above in the documentation? Thanks
